apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sanenode-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sanenode-api
    spec:
      containers:
      - name: sanenode-api
        image: bryanmacfarlane/sanenode-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7770