apiVersion: v1
kind: Service
metadata:
  name: sanenode-api-service
  labels:
    app: sanenode-api
spec:
  selector:
    app: sanenode-api
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 7770
  type: LoadBalancer